### ISSUE TITLE
Expansion too big on 16''

### ISSUE THREAD

**Issue by KBtwentytwenty** [crissNb/Dynamic-Island-Sketchybar#12]
The most recent update has made the islands massive when expanding on my 16'' mbp., at least 3 times the size as before.  Not totally sure if it is on my part or an issue with the program. 

Great work though!

**Comment by crissNb** [comment]
Could you perhaps tell me which island features are affected with this issue (and what you've did to cause the issue)? I'd also like to see screenshots, if you can provide them.

**Comment by KBtwentytwenty** [comment]
I followed the updated readme for installation, that's it. However I am also using the default menubar, which could be the issue.
The screenshots show the default island being larger than the notch and then the size of the music island which is much larger than it was previously.

<img width="1728" alt="Screenshot 2022-10-15 at 11 23 06" src="https://user-images.githubusercontent.com/66142366/195981538-dfd5c166-77e4-4d08-9679-722280f3069a.png">
<img width="1728" alt="Screenshot 2022-10-15 at 11 23 47" src="https://user-images.githubusercontent.com/66142366/195981539-c6937028-7129-4f5e-8ab0-e0baa7bbb107.png">

**Comment by crissNb** [comment]
It seems like the dynamic island is being drawn below the macOS's status bar. I've added an option in `userconfig.sh` (with 8dc1577), where you can enable the `topmost` setting of the sketchybar. This will draw the dynamic island on top of the status bar, making it the right size.

Check `README.md` for how to make your `userconfig.sh` file and set the following: `P_DYNAMIC_ISLAND_TOPMOST=on`
