### ISSUE TITLE
Not working at all.

### ISSUE THREAD

**Issue by Axo1234** [crissNb/Dynamic-Island-Sketchybar#15]
the notch just does nothing, nothing is working. I am currently using a M2 MBA

**Comment by crissNb** [comment]
I've made a small mistake with writing the sketchybarrc.example file. 1e5e4f7 fixes this. You may need to try performing the command `brew services restart sketchybar` once again after the installation, though.
But please know that if you've been using dynamic island configs previously, you need to perform a full reinstallation. There has been a change to the example sketchybarrc config file.

**Comment by pencilcheck** [comment]
i'm on m1 mba, not working
