### ISSUE TITLE
Dynamic Island Doesn't Seem To Function

### ISSUE THREAD

**Issue by Gryzle** [crissNb/Dynamic-Island-Sketchybar#17]
There appears to be no functionality after installing on my 27" iMac after following all the directions and making sure everything is updated. I'm on the latest public version of macOS Ventura. Any ideas?

**Comment by crissNb** [comment]
There appears to be a bug in which the dynamic island doesn't function the first time you run it after the installation. Have you perhaps tried to restart the entire sketchybar by `brew services restart sketchybar`?

**Comment by Gryzle** [comment]
I have, I even restarted and tried it on a different device. Still won't work. Both running latest Ventura release.

**Comment by crissNb** [comment]
Can you try the newest commit? I think it might've been the notification being enabled (without it being implemented properly). I've disabled notifications by default now. If that doesn't work, could you perhaps stop the service using brew (`brew services stop sketchybar`) and run sketchybar from the command line (by just typing `sketchybar`)? Tell me if there are any errors.

**Comment by Gryzle** [comment]
<img width="638" alt="Screenshot 2022-11-12 at 2 14 04 PM" src="https://user-images.githubusercontent.com/51198087/201490856-1ee45e63-3112-49d4-bc08-3d22c358e21c.png">

After stopping the service and starting it again, I got the request to access "Music," however, then I got the error in the screenshot above.

**Comment by crissNb** [comment]
I've added a new line in the sketchybarrc.example file that automatically builds the islandhelper program manually. I believe this will resolve this compatibility issue. You can either completely reinstall (by removing the entire sketchybar config folder), or add the new line from sketchybarrc.example manually (the line consists of "make").
If the issue still persists, let me know.

**Comment by Gryzle** [comment]
I don't see the error anymore when starting sketchy bar, but instead I see a new error:
<img width="348" alt="Screenshot 2022-11-12 at 2 29 14 PM" src="https://user-images.githubusercontent.com/51198087/201491334-3e41ef77-cfb2-4aec-beaf-43c39f24d4b3.png">

**Comment by crissNb** [comment]
This is because you already have a sketchybar instance running in the background. If you've started sketchybar using homebrew, you can stop sketchybar by `brew services stop sketchybar`or `killall sketchybar`.

**Comment by Gryzle** [comment]
Same error is back.
<img width="567" alt="Screenshot 2022-11-12 at 2 32 29 PM" src="https://user-images.githubusercontent.com/51198087/201491449-88e35c5a-52a5-43dc-a968-b81cf6fdef6f.png">

**Comment by Gryzle** [comment]
Note: It starts correctly using the `brew services start sketchybar` command but doesn't function, and doesn't start at all when using just `sketchybar` in the terminal.

**Comment by crissNb** [comment]
It seems like the islandhelper must be built again on a different CPU architecture (I've built the binary on a system with Apple Silicon). Could you try deleting islandhelper file by: `rm ~/.config/sketchybar/plugins/Dynamic-Island-Sketchybar/helper/islandhelper` and start sketchybar again? You may need to stop sketchybar and then start again for it to function.

**Comment by Gryzle** [comment]
It works now! However, only when launching via the `brew services start sketchybar` command, running `sketchybar` in the terminal results in the following error:
<img width="590" alt="Screenshot 2022-11-13 at 4 28 18 AM" src="https://user-images.githubusercontent.com/51198087/201515041-5e3f307f-6706-4146-aa06-8d8c1ad6b06d.png">

**Comment by Gryzle** [comment]
Here's my Intel island helper file (compressed to ZIP file for GitHub support):
[islandhelper.zip](https://github.com/crissNb/Dynamic-Island-Sketchybar/files/9996884/islandhelper.zip)

**Comment by crissNb** [comment]
> It works now! However, only when launching via the `brew services start sketchybar` command, running `sketchybar` in the terminal results in the following error

This doesn't seem like an error for me. It should work as intended

**Comment by pencilcheck** [comment]
i'm on 13 m1, tried suggestions but just got a black islandbar, not working
