### ISSUE TITLE
[Bug] Animations Run Slower On Non-Primary Display

### ISSUE THREAD

**Issue by Gryzle** [crissNb/Dynamic-Island-Sketchybar#18]
When using more than one monitor, the dynamic peninsula on the second display runs slower (animation-wise) compared to the primary display.

**Comment by crissNb** [comment]
From ReadMe FAQ section:
> This project is not intended to be used with multiple monitors.

With that being said, I think if anything I'll make the dynamic island only appear on one display (either a primary display or an active display).

**Comment by Gryzle** [comment]
I know that it's only intended for one display, but as you said, it should only be displayed on one display. This should 100% be the **primary** display, not the active display, because the constant switching of displays would make the notch become annoying, especially when it's intended to be stationary when it's an actual display cutout.

**Comment by crissNb** [comment]
Agreed. Will be making the changes over this week.

**Comment by albert-ying** [comment]
> I'll make the dynamic island only appear on one display (either a primary display or an active display).

Is it possible to make it configurable? I personally would prefer to have it on the active display (instead of a fixed display)

**Comment by crissNb** [comment]
Yes of course, I'll add a variable tomorrow so the setting can be changed in `userconfig.sh`

**Comment by crissNb** [comment]
I have implemented the changes. The default setting is still set to "Primary", so you should change the setting `P_DYNAMIC_ISLAND_DISPLAY` to `Active` in userconfig.sh.
Because I made changes to `userconfig.sh`, you'll need to either recopy the userconfig.sh in the repository to `~/.config/userconfig.sh` (see readme for more info) or add the line manually.

**Comment by albert-ying** [comment]
Thank you so much!
