### ISSUE TITLE
Config for 16" notch?

### ISSUE THREAD

**Issue by marcusramberg** [crissNb/Dynamic-Island-Sketchybar#19]
Been trying to tweak this for 16" mbp, but I can't seem to make the notifications big enough. Anyone have a working config?

**Comment by Yukig59** [comment]
[userconfig.txt](https://github.com/crissNb/Dynamic-Island-Sketchybar/files/10307327/userconfig.txt)
@crissNb Hey mate ! 
I'm using your project on my Macbook pro 16", and I edited some values to make it work on my device. Notifications are still broken (seems you know it) and spotify only display a blank island. 
Apps names are displaying well tho. 
You'll find the config file attached to this, in a txt format (sh wasn't uploading)
Feel free if you wanna know anything, happy to help. 
Cheers
Yuki

**Comment by crissNb** [comment]
Thank you. I've added your configuration file (after adjusting one or two defaults to stay consistent) in userconfigs/ directory. As of right now, users need to manually copy the right config file for themselves (see readme installation section for more details).

Maybe in the future I'll make changing between config presets easier. Closing this issue for now.
