### ISSUE TITLE
Positioning with M2 MBA

### ISSUE THREAD

**Issue by drakaintdead** [crissNb/Dynamic-Island-Sketchybar#2]
The island doesn't work properly on an M2 MBA. The notch is slightly too wide on the sides, and it doesn't open properly. Also the music popup shows once when I launch it, but never again.

**Comment by crissNb** [comment]
I suspected the M2 MBAs to have different notch sizes. I'll be making a proper global config file so that the notch size can be adjusted for different MacBooks (or even hide the notch for those without the notch).
The music popup one sounds like a bug. I was able to reproduce the bug and seems like I need to fix. As a temporary "fix", you can always restart sketchybar with: `brew services restart sketchybar`

**Comment by drakaintdead** [comment]
Thanks! Can't wait to be able to properly use the bar, it seems awesome!

**Comment by 112cxyz** [comment]
I have a similar issue on my MBP 2017, I also get extreme lag and it causes my system to lag.

**Comment by crissNb** [comment]
> I also get extreme lag and it causes my system to lag.

This is something interesting. My guess is that this might have to do something with notifications module (as that's the least optimised, heaviest module as of right now). Could you perhaps disable the notification module? You can do this by going to `~/.config/sketchybar/plugins/dynamic_island/dynamic_island.sh` and comment out the following line:
```bash
bash "$HOME/.config/sketchybar/plugins/dynamic_island/islands/notification/handler.sh"
```

**Comment by 112cxyz** [comment]
I commented it out and it severely reduced lag. However, there are still graphical glitches with the menu bar shown & hidden 

Shown:
https://user-images.githubusercontent.com/78795456/193688947-3d011732-6ca1-47ee-8a62-ca0d54b226e9.mov

Hidden:
https://user-images.githubusercontent.com/78795456/193688826-21d3d675-a844-4328-a504-cdf610d7a481.mov

**Comment by crissNb** [comment]
Unfortunately, this configuration is meant to be used just with SketchyBar (without the macOS menu bar). See "optimal setup" part in readme for more info.
As for the graphical glitches when the menu bar is hidden, could you try the latest commit? If not, I think it would be better if you could open up a new issue.

**Comment by crissNb** [comment]
I have implemented a "better" system to configure the notch with 90b641f. The configuration file is still in a very rough shape, though. In "rough shape" I mean users have to go through trial and error and find the perfect notch size for their MacBook with a notch. You can now configure the notch to be in a different size more easily, as well as the modules.
Once I gather enough data for different configuration files from users, I think a preset system can be implemented.
