### ISSUE TITLE
Segmentation Fault for islandhelper / Ventura 13.1 arm64/MacBookPro 

### ISSUE THREAD

**Issue by jonathanwilner** [crissNb/Dynamic-Island-Sketchybar#21]
Hi,

This is an amazing plugin ! Thank you for building it and sharing it with the world. I love using it with SketchyBar. I updated to the latest code from master & I'm getting a segmentation fault trying to run the islandhelper. 

lldb produces:

Process 14840 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010000384c islandhelper`main + 48
islandhelper`main:
->  0x10000384c <+48>: ldrb   w8, [x0]
    0x100003850 <+52>: cmp    w8, #0x31
    0x100003854 <+56>: b.ne   0x10000389c               ; <+128>
    0x100003858 <+60>: adr    x0, #0x358                ; DBPATH_CMD
Target 0: (islandhelper) stopped.

**Comment by crissNb** [comment]
Running the program outside of a debugger (and outside of sketchybar) seems to be working correctly (freshly installed config) on my end.

The debugger produces that error because the environment variable "P_DYNAMIC_ISLAND_NOTIFICATION_ENABLED" has not been set. When running the helper program via the sketchybarrc, this is not the case, as the config file exports this variable (config file is sourced).

**Comment by jonathanwilner** [comment]
Hi,

Good to know re the Env variable ! Makes sense.

I only brought the debugger up because I’m getting a crash attempting to
run it in a previously working .sketchybarrc and I saw the segfault as a
reason sketchybar didn’t start. I will check my config and see if that env
variable maybe isn’t getting set…

Thanks for the amazingly fast response !

**Comment by jonathanwilner** [comment]
Got it - it was the variable. I had not updated the config based on the new sketchybarrc. 

Still getting some sort of an error I can't track down - 

"Parse error: bad token <stdin>:1

But it's not preventing Dynamic Island from loading - it just seems that any error in Sketchybar will keep it from hiding itself from the native MacOS menubar when a user moves up to the top.

**Comment by crissNb** [comment]
I'm a bit confused. Could you elaborate (perhaps share a short clip of what's happening)?
I've resolved the parse error with my latest commit, but from what I've seen it shouldn't have any impact on Dynamic Island's behaviour.

**Comment by jonathanwilner** [comment]
Hi -

Thanks for following up ! I am sorry that I confused two things. The parse error is coming from the plugin, thank you for fixing it!

Sketchybar was not hiding because I needed for some reason to adjust the setting for topmost in order to have the bar autohide. I didn't have that in the configuration before.

**Comment by crissNb** [comment]
I'm glad you fixed your issue. Closing this issue.
