### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by bahman777** [crissNb/Dynamic-Island-Sketchybar#22]
Notifications stop working after about 5 minutes. It can open the db sqlite3, but cannot access as it says database cannot be opened. It works well for the first 5 minutes or so, then no notifications.

**Comment by crissNb** [comment]
I just made a commit that hopefully fixes this issue. If you encounter the same problem again, feel free to reopen this issue

**Comment by bahman777** [comment]
Thank you. I am afraid the issue persists. The error occurs on the database count. Looks like after a number of calls, it starts failing. Really love how it works.

**Comment by crissNb** [comment]
I've added a commit that should hopefully fix this (again). I will definitely be doing extended testing sessions to see if they break after a certain period.
Overall the code turned out to be pretty messy so I'll need to cleanup the code for certain, though.
