### ISSUE TITLE
Layout bugging out 

### ISSUE THREAD

**Issue by priyanshuppal** [crissNb/Dynamic-Island-Sketchybar#24]
Hi there, 

I am very new to this and unsure whats going wrong but im unable to figure out why the island bugs out and just stiops working. its still displaying behind the notch but its not reacting to any changes like brightness, volume, music or app change. have to manually restart it and it still sometimes doesnt work. any input is appreciated.

**Comment by crissNb** [comment]
If all features stop working all of the sudden, it sounds like there is a problem with the helper program. Could you perhaps run `sketchybar` in Terminal and send me the output when it stops working?

**Comment by priyanshuppal** [comment]
it may have been fixed by upgrading to ventura. i just got this refurbished macbook and it came with monterey. havent had any issues yet. will post if any found

**Comment by priyanshuppal** [comment]
quick thing. it says command not found for jq in shell script. any idea what it may be?
<img width="979" alt="Screenshot 2023-01-27 at 7 17 43 pm" src="https://user-images.githubusercontent.com/60973845/215045245-8340e28e-35b8-414b-9a21-c9e25fadf341.png">

**Comment by crissNb** [comment]
`jq` is a prerequisite. You need to install it via `brew install jq`.

I forgot to add `jq` in requirements, will do it now. Closing
