### ISSUE TITLE
Pipe broken error when turning on notification island

### ISSUE THREAD

**Issue by priyanshuppal** [crissNb/Dynamic-Island-Sketchybar#25]
Hi Again, 

I was experimenting and came across a weird error where it says that the pipe is broken for stdout 

<img width="246" alt="Screenshot 2023-01-27 at 8 19 42 pm" src="https://user-images.githubusercontent.com/60973845/215057130-9922364f-57ef-4c66-ba2e-d4d881690864.png">

**Comment by priyanshuppal** [comment]
another thing i found is that whenever resuming music, the r always gets cut off. is there a way to change where it is displayed. ive tried but had no luck

**Comment by crissNb** [comment]
> that the pipe is broken for stdout

Although this is an unexpected output, it shouldn't affect the core functionality of this project.

> the r always gets cut off.

You may have to tweak some of the settings. The default settings are for MBP 14 inch 2021 (there's also an option for MBP 16 inch 2021). You can tweak the settings by modifying `userconfig.sh` (see readme for more details). I understand most values require tedious process to determine, it is normal to go through trial and error.
