### ISSUE TITLE
How do i uninstall it

### ISSUE THREAD

**Issue by AsedaDeveloper** [crissNb/Dynamic-Island-Sketchybar#30]

**Comment by crissNb** [comment]
Uninstallation can be done by simply removing the `Dynamic-Island-Sketchybar` folder and the `userconfig.sh` located in your `~/.config/sketchybar/plugins` and `~/.config/sketchybar/userconfig.sh` respectively. So something like:
```bash
rm -rf ~/.config/sketchybar/plugins/Dynamic-Island-Sketchybar
rm ~/.config/sketchybar/userconfig.sh
```

You also need to remove the relevant lines you have added in your `~/.config/sketchybar/sketchybarrc`

**Comment by yemreak** [comment]
@crissNb  Could you append this instruction to your README file
