### ISSUE TITLE
dynamic music suggestion

### ISSUE THREAD

**Issue by minksW** [crissNb/Dynamic-Island-Sketchybar#34]
like when the music plays, make it like show it in the dynamic island with a live visualizer and the song vinyl
and add more features to more apps #

**Comment by crissNb** [comment]
I think that could be doable, but I'm not sure if it should display the music at all times. I could do it so that the island expands when you hover on top of it.

**Comment by AISLVE** [comment]
Yeah i think you should do this @crissNb will look more cool xd
