### ISSUE TITLE
item.sh Overriding Sketchybarrc Bar properties

### ISSUE THREAD

**Issue by khaneliman** [crissNb/Dynamic-Island-Sketchybar#35]
Hey, I noticed that there was a [commit](https://github.com/crissNb/Dynamic-Island-Sketchybar/commit/9906f28ee5dff56959a5bc74b9168fffb6ff9293#diff-1d1fe63b206f6d4502458538e1ca65ac154deb7c0869c61f2c753ecdbc0de243R52) for adding the sketchybar --bar config to the item.sh. It will override a user's sketchybarrc config changing the layout/theme of their actual sketchybar bar instead of just the dynamic island. I think I see the intention and just wanted to verify and see if we could utilize variables instead of hard coding some values to support user customization. 

Without sketchybar --bar commit: (custom offsets and theming)
<img width="1512" alt="image" src="https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/1778670/d93efe54-fad1-49d4-8738-36e14d996138">

With sketchybar --bar commit: (anchored to top and transparent)
<img width="1512" alt="image" src="https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/1778670/62c8bfd2-a07f-4406-b861-6b470957f59e">

I assume the intention was to try and make the dynamic island come from the actual top of the screen and be invisible until invoked?

**Comment by crissNb** [comment]
There had to be some `--bar`` config and `--defaults` configured when the user would like to use the Dynamic Island without any other `sketchybarrc` modules. But I agree, it makes sense that the `--bar` settings conflict for existing users.

A solution that I'm thinking for a while for this is to have the Dynamic Island running as an another instance of `SketchyBar` (using its multi-bar support). This way the Dynamic Island will be consistent across all existing `Sketchybar` users.

**Comment by khaneliman** [comment]
So it looks like we just need to tell user to clone into a separate config directory and do a custom symlink or create a simple bootstrapping script. 
ln -s $(which sketchybar) $(dirname $(which sketchybar))/dynamic-island && git clone https://github.com/crissNb/Dynamic-Island-Sketchybar.git ~/.config/dynamic-island

**Comment by crissNb** [comment]
I've made the Dynamic Island separate from the regular SketchyBar config. It seems to work fine on my end. Could you let me know if there's still problem on your end?

**Comment by khaneliman** [comment]
> I've made the Dynamic Island separate from the regular SketchyBar config. It seems to work fine on my end. Could you let me know if there's still problem on your end?

Sorry, haven't used my laptop in a few days. Latest commit works well for me with keeping my standard bar config in tact and the dynamic island looks better now too since it's anchored where it wants to be.
