### ISSUE TITLE
Small bit of glitching.

### ISSUE THREAD

**Issue by maxdalat** [crissNb/Dynamic-Island-Sketchybar#39]
Whenever I preform any action, there is a tiny bit of glitching happening where there is a square only on the left side that shows through the island into my background. Here is my config. {Rename extension to .sh, GitHub wouldn't let me upload a .sh file}

Also, I am running a 13in, M2 Mac (with the notch), and the settings I have made are like 95% good, but there are tiny discrepancies.

[userconfig.txt](https://github.com/crissNb/Dynamic-Island-Sketchybar/files/11916405/userconfig.txt)

**Comment by crissNb** [comment]
Could you perhaps provide a small recording presenting the issue?

https://github.com/crissNb/Dynamic-Island-Sketchybar/blob/main/userconfigs/mba2022_13.sh

Someone has already made a configuration file for M2 MacBook Air. Could you perhaps try this configuration file as well? I don't own the device so I don't know which one works better.

**Comment by maxdalat** [comment]
Uploading Screen Recording 2023-06-30 at 6.19.28 PM 4.MOV…

https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/63883235/42416ba7-abb2-4ea1-ba16-748ef83ba302

Here are some examples.

**Comment by maxdalat** [comment]
I tried the configuration you provided, I prefer mine since the other one only has music controls, and extends the notch. Although the issue still persists, meaning that it most likely did not come from the user config file.

**Comment by crissNb** [comment]
Unfortunately, I can't seem to reproduce the issue on my end (MBP 2021 M1 Pro, macOS 13.4.1). I'm assuming this happens with clean install of sketchybar and dynamic island.

Part of me is also wondering if this is an issue towards sketchybar and not the configuration files I've built for it.

**Comment by crissNb** [comment]
With the new config changes and different implementation of the island behavior, I believe this issue no longer occurs. Closing for now.
