### ISSUE TITLE
blur?

### ISSUE THREAD

**Issue by sasa8810** [crissNb/Dynamic-Island-Sketchybar#42]
<img width="421" alt="スクリーンショット 2023-07-18 15 05 56" src="https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/91324887/3612fafe-bbca-47a5-9f80-84f017e912c0">
is there anyway to fix the shadow?

**Comment by crissNb** [comment]
This is most likely happening if you have your `topmost` setting for your other sketchybar enabled. Either set this to disable, or use run `dynamic-island-sketchybar` before your sketchybar loads. You can do this by:

```bash
dynamic-island-sketchybar &

# load your sketchybar config here```
