### ISSUE TITLE
'dynamic-island-sketchybar' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by Ahwxorg** [crissNb/Dynamic-Island-Sketchybar#44]
Hey there,

I followed the instructions, and I set `P_DYNAMIC_ISLAND_DISPLAY` to `All`.

<img width="877" alt="image" src="https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/87855602/f1190521-3ef1-4779-880b-5ba9892f6c82">

What do I do?

**Comment by crissNb** [comment]
`P_DYNAMIC_ISLAND_DISPLAY` needs to be set to `all` (with small 'a', case sensitive).
Otherwise, do you have `notification island` feature enabled? If so, could you turn it off and try it? This feature is still experimental.

**Comment by Ahwxorg** [comment]
I have `P_DYNAMIC_ISLAND_DISPLAY` set to `all` now, didn't change anything. Tried disabling everything over here:
```sh
# Enable/Disable Islands
P_DYNAMIC_ISLAND_MUSIC_ENABLED=1
P_DYNAMIC_ISLAND_APPSWITCH_ENABLED=1
export P_DYNAMIC_ISLAND_NOTIFICATION_ENABLED=0
P_DYNAMIC_ISLAND_VOLUME_ENABLED=1
P_DYNAMIC_ISLAND_BRIGHTNESS_ENABLED=1
P_DYNAMIC_ISLAND_WIFI_ENABLED=1
P_DYNAMIC_ISLAND_POWER_ENABLED=1
```

That also didn't change anything. I don't have Sketchybar running at the moment.

**Comment by crissNb** [comment]
Interesting, I'm unable to reproduce the issue on my device (clean install). I'll have a look into this issue more in depth this weekend.

**Comment by Ahwxorg** [comment]
Okay, so apparently I just needed to reboot...

I'm sorry. Should have tried before creating the issue!

~Have you tried turning it on and off again?~
