### ISSUE TITLE
Music thumbnail bug with the latest commit changes

### ISSUE THREAD

**Issue by AISLVE** [crissNb/Dynamic-Island-Sketchybar#47]
![Screenshot 3](https://github.com/crissNb/Dynamic-Island-Sketchybar/assets/121119257/4a318f46-67ca-43b7-b457-6438b4b89618)
Also the image is not being updated, only 1 image is shown(is it is not blank) even tho the song is different

**Comment by AISLVE** [comment]
@crissNb

**Comment by AISLVE** [comment]
music
{
  "Player State" : "Playing",
  "Name" : "Circles",
  "Track ID" : "spotify:track:21jGcNKet2qwijlDFuPiPb",
  "Album" : "Hollywood's Bleeding",
  "Disc Number" : 1,
  "Play Count" : 0,
  "Popularity" : 88,
  "Has Artwork" : true,
  "Duration" : 215280,
  "Artist" : "Post Malone",
  "Album Artist" : "Post Malone",
  "Playback Position" : 0.0040000001899898052,
  "Track Number" : 6
}
curl: option -o: is badly used here
curl: try 'curl --help' for more information

**Comment by AISLVE** [comment]
also, the thumbnail is sunk inside notch, almost 5%

**Comment by crissNb** [comment]
The thumbnail "sinking inside notch" can be prevented by adjusting the `P_DYNAMIC_ISLAND_MUSIC_IDLE_EXPAND_WIDTH` value.
