### ISSUE TITLE
P_DYNAMIC_ISLAND_MONITOR_HORIZONTAL_RESOLUTION issue

### ISSUE THREAD

**Issue by SmartGecko44** [crissNb/Dynamic-Island-Sketchybar#52]
When I change the P_DYNAMIC_ISLAND_MONITOR_HORIZONTAL_RESOLUTION to the appropriate size (1440) for my MBA 15" 2023, the notch gets bigger instead of smaller. Even with the P_DYNAMIC_ISLAND_DEFAULT_WIDTH set to 1, it is still about 5cm to wide on each side.

**Comment by priyanshuppal** [comment]
I've been using negative values for my personal config. Think I was using -35 from memory

**Comment by SmartGecko44** [comment]
Thanks, for some reason I didn't think of using negative numbers.
