### ISSUE TITLE
frequent crashes

### ISSUE THREAD

**Issue by Jimnnm** [crissNb/Dynamic-Island-Sketchybar#60]
I'm loving the app, its extremely light weight and the animations feel very stock and fluid, but I'm having a few problems

The app crashes frequently when changing settings,

also is it possible to change the base size of the notch while keeping its extended size? its way too big by default but decreasing the size in the settings to match the 14" macbook notch, some of the content becomes covered by the physical notch.

using the gui version off gumroad, not sure how to send logs and helpful info about the crashes.

**Comment by crissNb** [comment]
Fixed with v1.0.4
