### ISSUE TITLE
Im stupid and don't understand the installation  

### ISSUE THREAD

**Issue by Alex-sys-sys** [crissNb/Dynamic-Island-Sketchybar#62]
Hi, I have a problem, I do not understand where from and where I should create the symlink in the installation process. I have sketchybar dir in ./config and there is a binary(it's named sketchybarrc, it was created after installation of sketchybar) in there, should I make a symlink of this binary in the same one sketchybar dir and then just clone the repo into ./config dir separately, as the commands say? I tried that and system does not even see a command 'dynamic-island-sketchybar'.
<img width="463" alt="Screenshot 2024-07-30 at 02 20 41" src="https://github.com/user-attachments/assets/8178e9d3-2e66-4c30-af93-60f376f0c940">

**Comment by crissNb** [comment]
sketchybarrc is not a binary file, instead it's more like a configuration file. Symlink needs to be created for the sketchybar binary itself. Running the command in the readme will create a symlink and place the symlink next to where the sketchybar installation happened.

**Comment by crissNb** [comment]
Installation can now be done with homebrew:
```bash
brew tap crissnb/dynamicisland
brew install DynamicIslandSketchybar
```

then, a userconfig.sh file must be copied to `~/.config/dynamic-island-sketchybar/userconfig.sh`.
```bash
cp /opt/homebrew/etc/dynamic-island-sketchybar/userconfigs/mbp2021_14.sh ~/.config/dynamic-island-sketchybar/userconfig.sh
```

(if the dynamic-island-sketchybar directory does not exist, create one)

and can be started with:
```bash
dynamic-island
```

See `README.md` for more details.
