### ISSUE TITLE
[FEATURE] Installation via homebrew

### ISSUE THREAD

**Issue by Romachamp** [crissNb/Dynamic-Island-Sketchybar#63]
I really like your app, but would like to install it via homebrew as most of my apps. Current installation process is a bit long and could be tricky for somebody, but homebrew one is much simpler and more efficient.

**Comment by xsova** [comment]
@crissNb I'd be open to making this work on homebrew

**Comment by crissNb** [comment]
Installation can now be done with homebrew:
```bash
brew tap crissnb/dynamicisland
brew install DynamicIslandSketchybar
```

then, a userconfig.sh file must be copied to `~/.config/dynamic-island-sketchybar/userconfig.sh`.
```bash
cp /opt/homebrew/etc/dynamic-island-sketchybar/userconfigs/mbp2021_14.sh ~/.config/dynamic-island-sketchybar/userconfig.sh
```

(if the dynamic-island-sketchybar directory does not exist, create one)

and can be started with:
```bash
dynamic-island
```

See `README.md` for more details.
