### ISSUE TITLE
Not conversant with Homebrew so install is hard. Managed Halfway...

### ISSUE THREAD

**Issue by KennethMwiti** [crissNb/Dynamic-Island-Sketchybar#64]
I got here:

Now a userconfig.sh file must be copied to ~/.config/dynamic-island-sketchybar/ directory. This can be done by copying an appropriate config file for your machine.

E.g. for 2021 MacBook Pro 14 Inch:

`cp ~/.config/dynamic-island-sketchybar/userconfigs/mbp2021_14.sh ~/.config/dynamic-island-sketchybar/userconfig.sh`

The file must be called userconfig.sh and located right under dynamic-island-sketchybar directory for dynamic island to function.

PLEASE HELP ME. THIS IS GIBBERISH TO ME  AND COPY PASTE SAYS NO SUCH FILE OR DIRECTORY

**Comment by crissNb** [comment]
Installation can now be done with homebrew:
```bash
brew tap crissnb/dynamicisland
brew install DynamicIslandSketchybar
```

then, a userconfig.sh file must be copied to `~/.config/dynamic-island-sketchybar/userconfig.sh`.
```bash
cp /opt/homebrew/etc/dynamic-island-sketchybar/userconfigs/mbp2021_14.sh ~/.config/dynamic-island-sketchybar/userconfig.sh
```

(if the dynamic-island-sketchybar directory does not exist, create one)

and can be started with:
```bash
dynamic-island
```

See `README.md` for more details.
