### ISSUE TITLE
Spotify support for music component

### ISSUE THREAD

**Issue by cagdassalur** [crissNb/Dynamic-Island-Sketchybar#8]
Is this planned?

Great stuff btw, really looking forward to see how this evolves

**Comment by cagdassalur** [comment]
@crissNb if i set the `P_DYNAMIC_ISLAND_MUSIC_SOURCE=Spotify` and echo `P_DYNAMIC_ISLAND_MUSIC_SOURCE`  and `MUSIC_SOURCE` both of them gets set to 'Music' after the first echo output. Was this working on your end?
I'm investigating the issue, just wanted to inform.

**Comment by crissNb** [comment]
It doesn't seem to be working on my end either (I thought it was fine when I tested it? I'm not sure what happened). Did you find a fix for this? Otherwise I'll be looking into solving this tomorrow

**Comment by cagdassalur** [comment]
my guess is it's because we're not passing env variables correctly in some place, possible in `reset.sh` or something, i couldn't find any decent cause though, waiting until i have more spare time

**Comment by 112cxyz** [comment]
I've made a osascript for Spotify work and I could look into making it work

**Comment by crissNb** [comment]
@112cxyz Will you be making a PR soon (which will be absolutely awesome)? Otherwise I could look into solving this problem  myself when I have spare time

**Comment by 112cxyz** [comment]
I will be later I’m just trying to fix random lag and also random bugs with
non downloaded album art. I have quite a busy day today but I’ll do it as
soon as I can

**Comment by crissNb** [comment]
Spotify seems to be working as intended after config rework, 99cdd84 (or at least on my end). Closing this issue for now
